apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: weather-app
spec:
  type: service
  owner: guests
  lifecycle: experimental
  system: test-app
  providesApis:
    - weather-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: weather-api
  description: Get the weather details based on your city
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  definition:
    $text: https://github.com/imprem/weather-app/blob/master/weather-app-api-swagger.json
