apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: weather-app
spec:
  type: service
  owner: guests
  lifecycle: experimental
  system: test-app
  apiConsumedBy: ['component:react-app1']
